DELIMITER $$
CREATE TRIGGER addultyCheck BEFORE INSERT ON Clients
FOR EACH ROW
BEGIN
IF (SELECT DATE_FORMAT(FROM_DAYS(DATEDIFF(NOW(),NEW.birthday)),'%Y') + 0 AS age) < 18
THEN
    SIGNAL SQLSTATE '45000'  SET MESSAGE_TEXT = 'To young to be a client';
END IF;

END$$
DELIMITER ;

